package ui;

import java.awt.event.ItemEvent;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kyran Adams
 */
@SuppressWarnings("serial")
public class ChessPanel extends JPanel {

	public JCheckBox aiToggle;
	public JPanel gamePanel;
	private JSplitPane jSplitPane1;
	private JButton loadButton;
	private JPanel menuPanel;
	private JButton newGameButton;
	private JButton saveButton;
	private JLabel titleLabel;
	private JButton undoButton;
	
	/**
	 * Creates new form ChessPanel
	 *
	 * @param gamePanel
	 */
	public ChessPanel(final JPanel gamePanel, final ChessUIResponder uiResponder) {
		initComponents(gamePanel, uiResponder);
		uiResponder.setChessPanel(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 *
	 * @param uiResponder
	 */
	private void initComponents(final JPanel panel, final ChessUIResponder uiResponder) {

		jSplitPane1 = new JSplitPane();
		menuPanel = new JPanel();
		newGameButton = new JButton();
		titleLabel = new JLabel();
		undoButton = new JButton();
		loadButton = new JButton();
		saveButton = new JButton();
		aiToggle = new JCheckBox();
		gamePanel = panel;

		newGameButton.setText("New Game");
		newGameButton.addActionListener(uiResponder::newGameClicked);

		titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
		titleLabel.setText("Java Chess");

		undoButton.setText("Undo");
		undoButton.addActionListener(uiResponder::undoClicked);

		loadButton.setText("Load");
		loadButton.addActionListener(uiResponder::loadClicked);

		saveButton.setText("Save");
		saveButton.addActionListener(uiResponder::saveClicked);

		aiToggle.setText("AI");
		aiToggle.addItemListener((r) -> uiResponder.aiSet(r.getStateChange() == ItemEvent.SELECTED));

		final GroupLayout menuPanelLayout = new GroupLayout(menuPanel);
		menuPanel.setLayout(menuPanelLayout);
		menuPanelLayout.setHorizontalGroup(menuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
				GroupLayout.Alignment.TRAILING,
				menuPanelLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								menuPanelLayout
						.createParallelGroup(GroupLayout.Alignment.TRAILING)
						.addComponent(titleLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
								GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(newGameButton, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(undoButton, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(loadButton, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(saveButton, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(aiToggle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)).addContainerGap()));
		menuPanelLayout.setVerticalGroup(menuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
				GroupLayout.Alignment.TRAILING,
				menuPanelLayout.createSequentialGroup().addContainerGap().addComponent(titleLabel)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE).addComponent(newGameButton)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(saveButton)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(loadButton)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(undoButton)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(aiToggle).addGap(10, 10, 10)));

		jSplitPane1.setLeftComponent(menuPanel);

		final GroupLayout gamePanelLayout = new GroupLayout(gamePanel);
		gamePanel.setLayout(gamePanelLayout);
		gamePanelLayout.setHorizontalGroup(gamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 293,
				Short.MAX_VALUE));
		gamePanelLayout.setVerticalGroup(gamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 298,
				Short.MAX_VALUE));

		jSplitPane1.setRightComponent(gamePanel);
		jSplitPane1.setEnabled(false);
		add(jSplitPane1);
	}
}
